'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useAuth } from '@/lib/auth-context';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Plus, FileText, Loader2, LogOut, Clock } from 'lucide-react';
import { toast } from 'sonner';

type Prescription = { id:string; tracking_code:string; status:string; created_at:string; expires_at:string; patient_note:string|null; city_name:string };
const labels: Record<string,{label:string;variant:'default'|'secondary'|'destructive'|'outline'}>={PENDING:{label:'در انتظار',variant:'secondary'},UNDER_REVIEW:{label:'در حال بررسی',variant:'outline'},HAS_OFFERS:{label:'پیشنهاد دارد',variant:'default'},PARTIAL_ACCEPTED:{label:'پذیرش جزئی',variant:'outline'},FULLY_ACCEPTED:{label:'تأمین شد',variant:'default'},EXPIRED:{label:'منقضی',variant:'destructive'},CANCELLED:{label:'لغو شده',variant:'destructive'}};
export default function PatientDashboard(){const router=useRouter();const {user,token,loading,logout}=useAuth();const [items,setItems]=useState<Prescription[]>([]);const [busy,setBusy]=useState(true);useEffect(()=>{if(!loading&&!user)router.push('/auth/login')},[loading,user,router]);useEffect(()=>{if(!token)return;fetch('/api/prescriptions',{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(d=>setItems(d.prescriptions||[])).catch(()=>toast.error('خطا در بارگذاری نسخه‌ها')).finally(()=>setBusy(false))},[token]);if(loading||!user)return <div className="flex min-h-[calc(100vh-4rem)] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary-600"/></div>;return <div className="mx-auto max-w-5xl px-4 py-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-background-900">نسخه‌های من</h1><p className="mt-1 text-sm text-background-600">مدیریت و پیگیری نسخه‌های دارویی</p></div><div className="flex gap-2"><Link href="/patient/prescriptions/new"><Button><Plus className="ml-2 h-4 w-4"/>ثبت نسخه جدید</Button></Link><Button variant="ghost" onClick={()=>{logout();router.push('/')}}><LogOut className="ml-2 h-4 w-4"/>خروج</Button></div></div><div className="mt-8">{busy?<div className="flex justify-center py-12"><Loader2 className="h-8 w-8 animate-spin text-primary-600"/></div>:items.length===0?<Card className="border-dashed"><CardContent className="flex flex-col items-center py-16"><FileText className="h-12 w-12 text-background-400"/><p className="mt-4 text-lg font-medium">هنوز نسخه‌ای ثبت نکرده‌اید</p><Link href="/patient/prescriptions/new" className="mt-6"><Button><Plus className="ml-2 h-4 w-4"/>ثبت نسخه جدید</Button></Link></CardContent></Card>:<div className="grid gap-4">{items.map(rx=>{const s=labels[rx.status]||{label:rx.status,variant:'outline' as const};return <Link key={rx.id} href={`/patient/prescriptions/${rx.id}`}><Card className="transition-all hover:border-primary-300 hover:shadow-md"><CardContent className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary-100 text-primary-700"><FileText className="h-5 w-5"/></div><div><p className="font-semibold" dir="ltr">{rx.tracking_code}</p><p className="text-sm text-background-600">{rx.city_name||'—'}</p></div></div><div className="flex items-center gap-3"><Badge variant={s.variant}>{s.label}</Badge><span className="text-xs text-background-500">{new Date(rx.created_at).toLocaleDateString('fa-IR')}</span></div></CardContent></Card></Link>})}</div>}</div></div>}
